Commands:
  permission-denied: '&cPermission Denied.'
  current-usage: '&cCurrent Usage: &4'
  player-offline: '&cTargeted player is offline.'

#Wurfelt Permissions:
  #Wurfelt.Admin - Admin Command of Wurfelt
Teleport:
  #Command: /tpa /tpaccept (/tpyes) /tpdeny (/tpno)
  #Permission: Wurfelt.Broadcast
  enable: true
Broadcast:
  #Command: /bc /broadcast
  #Permission: Wurfelt.Broadcast
  enable: true
  prefix: '&8[&3Alert&8] &7'
Vanish:
  #Command: /vanish /v
  #Permission: Wurfelt.Vanish
  enable: true
freeze:
  #Command: /freeze
  #Permission: Wurfelt.SS
  enable: true
  title: '&c客户端检查'
  freeze-message: '&a你的游戏进程已被一名在线的管理员冻结.'
  unfreeze-message: '&a您的客户端检查已经结束,感谢支持.'
  lore:
    - ' '
    - '&7您目前已被 &f[OPERATOR] &7锁定了客户端&7.'
    - '&7请配合我们完成客户端检查:'
    - ' '
    - '&7QQ群: &f828639514'
    - '&7Discord: &fhttps://discord.gg/R2XDZ3E'
    - ' '
    - '&7我们怀疑您正在使用不被允许的修改,请配合我们进行检查.'
    - '&c&l强制退出游戏会导致你被永久封禁!!!'
    - ' '
    - '&6Mirez.cn @ 2018'
  disconnect-message:
    - ' '
    - ' &6Monitoro &7remove a player in your server'
    - ' &7Because of &eRefuse Client Check &7.'
    - ' '
  command: 'ban [player] 30d 拒绝客户端检查'